### ISSUE TITLE
Vertaisarviointi #2

### ISSUE THREAD

**Issue by Jamb000h** [HoolaBoola/tsoha_article_library#2]
# Vertaisarviointi

Osa huomioista saattaa olla jo valmiiksi todo-listalla, mutta mennään suodattamattomana :)

## Käyttökokemus

Testasin sovellusta Herokussa. Käyttöliittymä näyttäisi olevan varsin pelkistetty, mutta toisaalta se myös sisältää oleelliset asiat. Käyttäjän luominen onnistui ongelmitta. Sain luotua artikkelin ohjeistuksen mukaisesti sekä käsin että lataamalla artikkelin URL:lla. Käyttökokemus katkesi hieman kun yritin mennä käyttäjäkohtaiseen listaukseen artikkeleista ja sain vastaani 404-sivun. Jonkinlainen navigaatio voisi myös olla hyödyksi - artikkelista pääsee pois vain selaimen painikkeilla. sain myös lisättyä artikkelin ilman syötteitä, mutta se oli kuitattu käyttöliittymässä ilmeisesti tarkoituksellisesti täyttämällä tyhjät kohdat tekstillä, joka kertoi että kohtaa ei oltu täytetty. Viimeinen huomio käyttökokemuksesta on se, että käyttöliittymässä on suomea ja englantia sekaisin.

## Keskeiset toiminnot

Kokeilin automaattista artikkelin hakemista kahdesti antamalla sivun URL:n. Taustalla käytetty kirjasto näytti toimivan varsin hyvin ja se onnistui noukkimaan artikkeleista halutut tiedot. Kaikki kohdat paitsi Author täyttyivät oikein - käyttöliittymäkoodin perusteella Authoria ei vielä täytetä automaattisesti.

Valittu WYSIWYG-kirjasto näyttäisi myös tekevän työnsä moitteetta sisällönsyöttövaiheessa. Kun artikkelia menee lukemaan, kaikki muotoilut boldia lukuunottamatta kuitenkin katoavat. Commit-historian perusteella WYSIWYG-editori on kuitenkin lisätty vastikään, joten sen tuottaman tulosteen muotoilu lienee vielä työn alla.

## Ohjelmakoodi ja ohjelman rakenne

Ohjelman rakenne on mielestäni varsin hyvä. Keskeiset toiminnot ovat varsin kirjastovoittoisia, mutta projektissa on käytetty JavaScriptiä käyttöliittymän parantemiseksi onnistuneesti - olin suorastaan onnellinen kun nappulaa painamalla artikkeli latautui URL:sta ilman ylimääräisiä sivulatauksia.

Python-koodin rakenne noudattaa hyvin esimerkkisovellusta ja tietokantakysely => dictionary -muunnokset vaikuttavat varsin käytännöllisiltä!

SQL-skeeman tulkkaaminen vaati hieman vaivaa (toisen issuen perusteella dumppi postgresista joten ymmärrettävää), mutta rakenne vaikuttaa järkevältä.

Ainoat mahdollisesti korjausta kaipaavat huomiot jotka keksin:
- user.py-tiedostossa on artikkelien hakemiseen liittyvää tavaraa - oma tiedosto artikkeleihin liittyville toiminnoille voisi olla paikallaan, samalla puhdistuisi lisää myös routes.py
- Olisiko get_article()-metodissa helpompi palauttaa yksi artikkeli-dict jolla olisi nuo templatelle annetut arvot. Koodi pysyisi hieman siistimpänä backend-puolella ilman että template kasvaisi liikaa ja jos artikkeliin tulee joskus lisää dataa, ei sitä tarvitsisi miettiä rajapinnassa lainkaan.

**Comment by HoolaBoola** [comment]
Kiitos vertaisarvioinnista. Suurimman osan pointeista tiedostin jo aiemmin mutta hyvä saada palautetta, että ei ole vain minun mielestäni ongelma. SQL-skeeman siistin myöhemmin, tällä hetkellä se on vain dump tietokannasta (helpottaa jos tekee muutoksia tietokantaan usein eikä välttämättä pysy niistä kärryillä enää :D)

Nuo viimeiset kaksi pointtia olivat myös varsin hyviä, pitää niitä miettiä 👍
